/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as supplyCoffeSol from "./SupplyCoffe.sol";
import type * as solmate from "./solmate";

export type { supplyCoffeSol };

export type { solmate };
export type { Token } from "./Token";
